add_rules("mode.debug", "mode.release")
set_languages("c++26")
add_files("src/*.cpp")
add_includedirs("include")
set_encodings("utf-8")

target("llvm")
    set_kind("binary")
    set_toolchains("clang")
    add_cxxflags("-stdlib=libc++")
    add_ldflags("-lc++")
    add_linkdirs("/usr/local/lib/x86_64-unknown-linux-gnu")
    add_rpathdirs("/usr/local/lib/x86_64-unknown-linux-gnu")

target("gnu")
    set_kind("binary")
    set_toolchains("gcc")
    add_cxxflags("-Wno-interference-size")
    add_linkdirs("/usr/local/lib/../lib64")
    add_rpathdirs("/usr/local/lib/../lib64")
